export const enum StockType {
  IMPORT = 01,
  PURCHASE = 02,
  RETURN = 03,
  STOCKMOVEMENT = 04,
  PROCESSING = 05,
  ADJUSTMENT = 06,
  SALE = 11,
  RETURN = 12,
  STOCKMOVEMENT = 13,
  PROCESSING = 14,
  DISCARDING = 15,
  ADJUSTMENT = 16,
}
